config/routes.rb
Rails.application.routes.draw do
  resources :inward_order_details do 
    post :inward, on: :member
  end
  resources :outward_order_details do 
    post :outward, on: :member
  end
  resources :outward_orders do
    get :orders_with_status, on: :collection
  end
  resources :inward_orders do
    get :orders_with_status, on: :collection
  end
  resources :storages do 
    get :empty_one, on: :collection
    get :empty_all, on: :collection
  end
  resources :stocks do
    post :item_stocks, on: :collection
  end
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'items#index'
end

app/models/inward_order_detail.rb
class InwardOrderDetail < ApplicationRecord
  belongs_to :inward_order, foreign_key: :order_number
  validates_presence_of :order_number, :item_number, :amount, :status
end

app/controllers/inward_order_details_controller.rb
class InwardOrderDetailsController < ApplicationController
  before_action :set_inward_order_detail, only: %i[ show edit update destroy inward ]
  protect_from_forgery with: :null_session

  # GET /inward_order_details or /inward_order_details.json
  def index
    @inward_order_details = InwardOrderDetail.all
  end

  # GET /inward_order_details/1 or /inward_order_details/1.json
  def show
  end

  # GET /inward_order_details/new
  def new
    @inward_order_detail = InwardOrderDetail.new
  end

  # GET /inward_order_details/1/edit
  def edit
  end

  # POST /inward_order_details or /inward_order_details.json
  def create
    @inward_order_detail = InwardOrderDetail.new(inward_order_detail_params)

    respond_to do |format|
      if @inward_order_detail.save
        format.html { redirect_to inward_order_detail_url(@inward_order_detail), notice: "Inward order detail was successfully created." }
        format.json { render :show, status: :created, location: @inward_order_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inward_order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inward_order_details/1 or /inward_order_details/1.json
  def update
    respond_to do |format|
      if @inward_order_detail.update(inward_order_detail_params)
        format.html { redirect_to inward_order_detail_url(@inward_order_detail), notice: "Inward order detail was successfully updated." }
        format.json { render :show, status: :ok, location: @inward_order_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inward_order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inward_order_details/1 or /inward_order_details/1.json
  def destroy
    @inward_order_detail.destroy

    respond_to do |format|
      format.html { redirect_to inward_order_details_url, notice: "Inward order detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def inward
    ActiveRecord::Base.transaction do
      update_stock
      update_storage
      update_item
      update_inward_order_detail
      update_inward_order
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inward_order_detail
      @inward_order_detail = InwardOrderDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inward_order_detail_params
      params.require(:inward_order_detail).permit(:order_number, :serial_number, :item_number, :amount, :status)
    end

    def update_stock
      @stock = Stock.new
      @stock.storage_id = params[:storage_id]
      @stock.item_number = @inward_order_detail.item_number
      @stock.amount = @inward_order_detail.amount
      @stock.save
    end

    def update_storage
      @storage = @stock.storage
      @storage.in_use = 1
      @storage.save
    end

    def update_item
      @item = @stock.item
      @item.amount = @item.amount+@stock.amount
      @item.save
    end

    def update_inward_order_details
      @inward_order_detail.status = "done"
      @inward_order_detail.save
    end

    def update_inward_order
      @inward_order = @inward_order_detail.inward_order
      p @inward_order
      @inward_order_details = @inward_order.inward_order_details
      @inward_order_details.each do |current_order_detail|
        if current_order_detail.status.equal?("initial")
          return
        end
      end
      @inward_order.status = "done"
      @inward_order.save
    end
end

app/helpers/inward_order_details_helper.rb
module InwardOrderDetailsHelper
end

app/views/inward_order_details/_form.html.erb
<%= form_with(model: inward_order_detail) do |form| %>
  <% if inward_order_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inward_order_detail.errors.count, "error") %> prohibited this inward_order_detail from being saved:</h2>

      <ul>
        <% inward_order_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_number, style: "display: block" %>
    <%= form.text_field :order_number %>
  </div>

  <div>
    <%= form.label :serial_number, style: "display: block" %>
    <%= form.text_field :serial_number %>
  </div>

  <div>
    <%= form.label :item_number, style: "display: block" %>
    <%= form.text_field :item_number %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inward_order_details/_inward_order_detail.html.erb
<div id="<%= dom_id inward_order_detail %>">
  <p>
    <strong>Order number:</strong>
    <%= inward_order_detail.order_number %>
  </p>

  <p>
    <strong>Serial number:</strong>
    <%= inward_order_detail.serial_number %>
  </p>

  <p>
    <strong>Item number:</strong>
    <%= inward_order_detail.item_number %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= inward_order_detail.amount %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= inward_order_detail.status %>
  </p>


</div>

app/views/inward_order_details/edit.html.erb
<h1>Editing inward order detail</h1>

<%= render "form", inward_order_detail: @inward_order_detail %>

<br>

<div>
  <%= link_to "Show this inward order detail", @inward_order_detail %> |
  <%= link_to "Back to inward order details", inward_order_details_path %>
</div>

app/views/inward_order_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inward order details</h1>

<div id="inward_order_details">
  <% @inward_order_details.each do |inward_order_detail| %>
    <%= render inward_order_detail %>
    <p>
      <%= link_to "Show this inward order detail", inward_order_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New inward order detail", new_inward_order_detail_path %>

app/views/inward_order_details/new.html.erb
<h1>New inward order detail</h1>

<%= render "form", inward_order_detail: @inward_order_detail %>

<br>

<div>
  <%= link_to "Back to inward order details", inward_order_details_path %>
</div>

app/views/inward_order_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inward_order_detail %>

<div>
  <%= link_to "Edit this inward order detail", edit_inward_order_detail_path(@inward_order_detail) %> |
  <%= link_to "Back to inward order details", inward_order_details_path %>

  <%= button_to "Destroy this inward order detail", @inward_order_detail, method: :delete %>
</div>