config/routes.rb
Rails.application.routes.draw do
  resources :inward_order_details do 
    post :inward, on: :member
  end
  resources :outward_order_details do 
    post :outward, on: :member
  end
  resources :outward_orders do
    get :orders_with_status, on: :collection
  end
  resources :inward_orders do
    get :orders_with_status, on: :collection
  end
  resources :storages do 
    get :empty_one, on: :collection
    get :empty_all, on: :collection
  end
  resources :stocks do
    post :item_stocks, on: :collection
  end
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'items#index'
end

app/models/outward_order_detail.rb
class OutwardOrderDetail < ApplicationRecord
  belongs_to :outward_order, foreign_key: :order_number
  validates_presence_of :order_number, :item_number, :amount, :status
end

app/controllers/outward_order_details_controller.rb
class OutwardOrderDetailsController < ApplicationController
  before_action :set_outward_order_detail, only: %i[ show edit update destroy outward ]
  protect_from_forgery with: :null_session

  # GET /outward_order_details or /outward_order_details.json
  def index
    @outward_order_details = OutwardOrderDetail.all
  end

  # GET /outward_order_details/1 or /outward_order_details/1.json
  def show
  end

  # GET /outward_order_details/new
  def new
    @outward_order_detail = OutwardOrderDetail.new
  end

  # GET /outward_order_details/1/edit
  def edit
  end

  # POST /outward_order_details or /outward_order_details.json
  def create
    @outward_order_detail = OutwardOrderDetail.new(outward_order_detail_params)

    respond_to do |format|
      if @outward_order_detail.save
        format.html { redirect_to outward_order_detail_url(@outward_order_detail), notice: "Outward order detail was successfully created." }
        format.json { render :show, status: :created, location: @outward_order_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @outward_order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outward_order_details/1 or /outward_order_details/1.json
  def update
    respond_to do |format|
      if @outward_order_detail.update(outward_order_detail_params)
        format.html { redirect_to outward_order_detail_url(@outward_order_detail), notice: "Outward order detail was successfully updated." }
        format.json { render :show, status: :ok, location: @outward_order_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @outward_order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outward_order_details/1 or /outward_order_details/1.json
  def destroy
    @outward_order_detail.destroy

    respond_to do |format|
      format.html { redirect_to outward_order_details_url, notice: "Outward order detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def outward
    ActiveRecord::Base.transaction do
      update_stock
      update_storage
      update_item
      update_outward_order_detail
      update_outward_order
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outward_order_detail
      @outward_order_detail = OutwardOrderDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def outward_order_detail_params
      params.require(:outward_order_detail).permit(:order_number, :serial_number, :item_number, :amount, :status)
    end

    def update_stock
      @stock = Stock.find(params[:storage_id])
      @stock.amount = @stock.amount-@outward_order_detail.amount
      if @stock.amount == 0
        @stock.delete
      else
        @stock.save
      end
    end

    def update_storage
      @storage = @stock.storage
      if @stock.amount == 0
        @storage.in_use = 0
        @storage.save
      end
    end

    def update_item
      @item = @stock.item
      @item.amount = @item.amount-@outward_order_detail.amount
      @item.save
    end

    def update_outward_order_detail
      @outward_order_detail.status = "done"
      @outward_order_detail.save
    end

    def update_outward_order
      @outward_order = @outward_order_detail.outward_order
      p @outward_order
      @outward_order_details = @outward_order.outward_order_details
      @outward_order_details.each do |current_order_detail|
        if current_order_detail.status.equal?("initial")
          return
        end
      end
      @outward_order.status = "done"
      @outward_order.save
    end

end

app/helpers/outward_order_details_helper.rb
module OutwardOrderDetailsHelper
end

app/views/outward_order_details/_form.html.erb
<%= form_with(model: outward_order_detail) do |form| %>
  <% if outward_order_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(outward_order_detail.errors.count, "error") %> prohibited this outward_order_detail from being saved:</h2>

      <ul>
        <% outward_order_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_number, style: "display: block" %>
    <%= form.text_field :order_number %>
  </div>

  <div>
    <%= form.label :serial_number, style: "display: block" %>
    <%= form.text_field :serial_number %>
  </div>

  <div>
    <%= form.label :item_number, style: "display: block" %>
    <%= form.text_field :item_number %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/outward_order_details/_outward_order_detail.html.erb
<div id="<%= dom_id outward_order_detail %>">
  <p>
    <strong>Order number:</strong>
    <%= outward_order_detail.order_number %>
  </p>

  <p>
    <strong>Serial number:</strong>
    <%= outward_order_detail.serial_number %>
  </p>

  <p>
    <strong>Item number:</strong>
    <%= outward_order_detail.item_number %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= outward_order_detail.amount %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= outward_order_detail.status %>
  </p>

</div>

app/views/outward_order_details/edit.html.erb
<h1>Editing outward order detail</h1>

<%= render "form", outward_order_detail: @outward_order_detail %>

<br>

<div>
  <%= link_to "Show this outward order detail", @outward_order_detail %> |
  <%= link_to "Back to outward order details", outward_order_details_path %>
</div>

app/views/outward_order_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Outward order details</h1>

<div id="outward_order_details">
  <% @outward_order_details.each do |outward_order_detail| %>
    <%= render outward_order_detail %>
    <p>
      <%= link_to "Show this outward order detail", outward_order_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New outward order detail", new_outward_order_detail_path %>

app/views/outward_order_details/new.html.erb
<h1>New outward order detail</h1>

<%= render "form", outward_order_detail: @outward_order_detail %>

<br>

<div>
  <%= link_to "Back to outward order details", outward_order_details_path %>
</div>

app/views/outward_order_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @outward_order_detail %>

<div>
  <%= link_to "Edit this outward order detail", edit_outward_order_detail_path(@outward_order_detail) %> |
  <%= link_to "Back to outward order details", outward_order_details_path %>

  <%= button_to "Destroy this outward order detail", @outward_order_detail, method: :delete %>
</div>