config/routes.rb
Rails.application.routes.draw do
  resources :inward_order_details do 
    post :inward, on: :member
  end
  resources :outward_order_details do 
    post :outward, on: :member
  end
  resources :outward_orders do
    get :orders_with_status, on: :collection
  end
  resources :inward_orders do
    get :orders_with_status, on: :collection
  end
  resources :storages do 
    get :empty_one, on: :collection
    get :empty_all, on: :collection
  end
  resources :stocks do
    post :item_stocks, on: :collection
  end
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'items#index'
end

app/models/outward_order.rb
class OutwardOrder < ApplicationRecord
  has_many :outward_order_details, primary_key: :order_number, foreign_key: :order_number
  validates_presence_of :order_number, :status

  def self.find_orders_by_status(status)
    Outward.where(status: status)
  end
end

app/controllers/outward_orders_controller.rb
class OutwardOrdersController < ApplicationController
  before_action :set_outward_order, only: %i[ show edit update destroy ]

  # GET /outward_orders or /outward_orders.json
  def index
    @outward_orders = OutwardOrder.all
  end

  # GET /outward_orders/1 or /outward_orders/1.json
  def show
  end

  # GET /outward_orders/new
  def new
    @outward_order = OutwardOrder.new
  end

  # GET /outward_orders/1/edit
  def edit
  end

  # POST /outward_orders or /outward_orders.json
  def create
    @outward_order = OutwardOrder.new(outward_order_params)

    respond_to do |format|
      if @outward_order.save
        format.html { redirect_to outward_order_url(@outward_order), notice: "Outward order was successfully created." }
        format.json { render :show, status: :created, location: @outward_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @outward_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outward_orders/1 or /outward_orders/1.json
  def update
    respond_to do |format|
      if @outward_order.update(outward_order_params)
        format.html { redirect_to outward_order_url(@outward_order), notice: "Outward order was successfully updated." }
        format.json { render :show, status: :ok, location: @outward_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @outward_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def orders_with_status
    render json: OutwardOrder.find_orders_by_status(params[:status])
  end

  # DELETE /outward_orders/1 or /outward_orders/1.json
  def destroy
    @outward_order.destroy

    respond_to do |format|
      format.html { redirect_to outward_orders_url, notice: "Outward order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outward_order
      @outward_order = OutwardOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def outward_order_params
      params.require(:outward_order).permit(:order_number, :status)
    end
end

app/helpers/outward_orders_helper.rb
module OutwardOrdersHelper
end

app/views/outward_orders/_form.html.erb
<%= form_with(model: outward_order) do |form| %>
  <% if outward_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(outward_order.errors.count, "error") %> prohibited this outward_order from being saved:</h2>

      <ul>
        <% outward_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_number, style: "display: block" %>
    <%= form.text_field :order_number %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/outward_orders/_outward_order.html.erb
<div id="<%= dom_id outward_order %>">
  <p>
    <strong>Order number:</strong>
    <%= outward_order.order_number %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= outward_order.status %>
  </p>

</div>

app/views/outward_orders/edit.html.erb
<h1>Editing outward order</h1>

<%= render "form", outward_order: @outward_order %>

<br>

<div>
  <%= link_to "Show this outward order", @outward_order %> |
  <%= link_to "Back to outward orders", outward_orders_path %>
</div>

app/views/outward_orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Outward orders</h1>

<div id="outward_orders">
  <% @outward_orders.each do |outward_order| %>
    <%= render outward_order %>
    <p>
      <%= link_to "Show this outward order", outward_order %>
    </p>
  <% end %>
</div>

<%= link_to "New outward order", new_outward_order_path %>

app/views/outward_orders/new.html.erb
<h1>New outward order</h1>

<%= render "form", outward_order: @outward_order %>

<br>

<div>
  <%= link_to "Back to outward orders", outward_orders_path %>
</div>

app/views/outward_orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @outward_order %>

<div>
  <%= link_to "Edit this outward order", edit_outward_order_path(@outward_order) %> |
  <%= link_to "Back to outward orders", outward_orders_path %>

  <%= button_to "Destroy this outward order", @outward_order, method: :delete %>
</div>